# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindex',
            name='data_type',
            field=models.CharField(choices=[('int', 'int'), ('float', 'float'), ('str', 'string')], default='int', max_length=32, verbose_name='指标数据类型'),
        ),
    ]
